workspace(name = "com_github_rnburn_zipkin_opentracing")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_opentracing_cpp",
    remote = "https://github.com/opentracing/opentracing-cpp",
    commit = "06b57f48ded1fa3bdd3d4346f6ef29e40e08eaf5",
)

new_local_repository(
    name = "se_haxx_curl_libcurl",
    path = "/usr",
    build_file = "BUILD.curl"
)
